import { NextRequest, NextResponse } from 'next/server';

// ── Mock admin interviewers list (includes all statuses) ──
const MOCK_ADMIN_INTERVIEWERS = [
  // ── PENDING ──
  {
    id: 'adm-001',
    fullName: 'Talal Al-Bugami',
    fullNameAr: 'طلال البقمي',
    email: 'talal@example.com',
    phone: '+966501234001',
    status: 'PENDING',
    priceTier: 'STANDARD',
    specialties: 'SOFTWARE_ENGINEER',
    industries: 'TECHNOLOGY,STARTUPS',
    languages: 'AR,EN',
    yearsExperience: 4,
    rating: 0,
    totalInterviews: 0,
    appliedAt: '2024-12-01T10:30:00Z',
    idVerified: false,
    bio: 'Software engineer passionate about building scalable systems. Focused on backend development and cloud architecture.',
    bioAr: 'مهندس برمجيات شغوف ببناء الأنظمة القابلة للتوسع. متخصص في تطوير الخلفية والهندسة السحابية.',
    linkedInUrl: 'https://linkedin.com/in/talal-bugami',
    videoIntroUrl: null,
  },
  {
    id: 'adm-002',
    fullName: 'Reem Al-Shehri',
    fullNameAr: 'ريم الشهري',
    email: 'reem@example.com',
    phone: '+966501234002',
    status: 'PENDING',
    priceTier: 'PREMIUM',
    specialties: 'HR_MANAGER,CUSTOMER_SERVICE',
    industries: 'HUMAN_RESOURCES,CONSULTING',
    languages: 'AR',
    yearsExperience: 8,
    rating: 0,
    totalInterviews: 0,
    appliedAt: '2024-12-03T14:15:00Z',
    idVerified: true,
    bio: 'HR professional with deep expertise in talent acquisition, employee engagement, and organizational development.',
    bioAr: 'أخصائية موارد بشرية بخبرة واسعة في استقطاب المواهب وتطوير المنظمات.',
    linkedInUrl: 'https://linkedin.com/in/reem-alshehri',
    videoIntroUrl: null,
  },
  {
    id: 'adm-003',
    fullName: 'Faisal Al-Ghamdi',
    fullNameAr: 'فيصل الغامدي',
    email: 'faisal@example.com',
    phone: '+966501234003',
    status: 'PENDING',
    priceTier: 'STANDARD',
    specialties: 'SALES_MANAGER',
    industries: 'RETAIL,E_COMMERCE',
    languages: 'AR,EN',
    yearsExperience: 5,
    rating: 0,
    totalInterviews: 0,
    appliedAt: '2024-12-05T09:00:00Z',
    idVerified: true,
    bio: 'Sales leader with a track record of growing revenue in retail and e-commerce sectors.',
    bioAr: 'قائد مبيعات بسجل حافل في نمو الإيرادات في قطاعي التجزئة والتجارة الإلكترونية.',
    linkedInUrl: null,
    videoIntroUrl: null,
  },
  // ── APPROVED ──
  {
    id: 'int-001',
    fullName: 'Fahd Al-Rashed',
    fullNameAr: 'فهد الراشد',
    email: 'fahd@example.com',
    phone: '+966501234010',
    status: 'APPROVED',
    priceTier: 'ELITE',
    specialties: 'SOFTWARE_ENGINEER,PROJECT_MANAGER',
    industries: 'TECHNOLOGY,FINANCE',
    languages: 'AR,EN',
    yearsExperience: 12,
    rating: 4.9,
    totalInterviews: 87,
    appliedAt: '2024-06-15T10:00:00Z',
    idVerified: true,
    bio: 'Senior software architect and certified PMP with 12+ years leading engineering teams at scale.',
    bioAr: 'مهندس برمجيات أول وحاصل على شهادة PMP مع أكثر من 12 عاماً في قيادة فرق هندسية.',
    linkedInUrl: 'https://linkedin.com/in/fahd-alrashed',
    videoIntroUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  },
  {
    id: 'int-002',
    fullName: 'Maryam Al-Otaibi',
    fullNameAr: 'مريم العتيبي',
    email: 'maryam@example.com',
    phone: '+966501234011',
    status: 'APPROVED',
    priceTier: 'PREMIUM',
    specialties: 'HR_MANAGER,CUSTOMER_SERVICE',
    industries: 'HUMAN_RESOURCES,HEALTHCARE',
    languages: 'AR',
    yearsExperience: 15,
    rating: 4.8,
    totalInterviews: 134,
    appliedAt: '2024-05-20T10:00:00Z',
    idVerified: true,
    bio: 'Award-winning HR executive with 15 years across healthcare and government sectors. SHRM-SCP certified.',
    bioAr: 'مديرة موارد بشرية حائزة على جوائز مع 15 عاماً في قطاعي الصحة والحكومة.',
    linkedInUrl: 'https://linkedin.com/in/maryam-alotaibi',
    videoIntroUrl: null,
  },
  {
    id: 'int-003',
    fullName: 'Sultan Al-Harbi',
    fullNameAr: 'سلطان الحربي',
    email: 'sultan@example.com',
    phone: '+966501234012',
    status: 'APPROVED',
    priceTier: 'PREMIUM',
    specialties: 'MARKETING_SPECIALIST,SALES_MANAGER',
    industries: 'MARKETING,E_COMMERCE',
    languages: 'AR,EN',
    yearsExperience: 10,
    rating: 4.7,
    totalInterviews: 62,
    appliedAt: '2024-07-01T10:00:00Z',
    idVerified: true,
    bio: 'Growth marketing expert specializing in B2B SaaS and e-commerce. Ex-Google, Ex-Careem.',
    bioAr: 'خبير تسويق نمو متخصص في برمجيات الأعمال والتجارة الإلكترونية.',
    linkedInUrl: 'https://linkedin.com/in/sultan-alharbi',
    videoIntroUrl: null,
  },
  {
    id: 'int-004',
    fullName: 'Aisha Al-Dosari',
    fullNameAr: 'عائشة الدوسري',
    email: 'aisha@example.com',
    phone: '+966501234013',
    status: 'APPROVED',
    priceTier: 'STANDARD',
    specialties: 'ACCOUNTANT,DATA_ANALYST',
    industries: 'FINANCE,CONSULTING',
    languages: 'AR',
    yearsExperience: 15,
    rating: 4.6,
    totalInterviews: 45,
    appliedAt: '2024-08-10T10:00:00Z',
    idVerified: true,
    bio: 'CPA-certified accountant and data analytics professional with 15 years in financial consulting.',
    bioAr: 'محاسب معتمد ومحلل بيانات مع 15 عاماً في الاستشارات المالية.',
    linkedInUrl: null,
    videoIntroUrl: null,
  },
  {
    id: 'int-005',
    fullName: 'Khalid Al-Mutairi',
    fullNameAr: 'خالد المطيري',
    email: 'khalid@example.com',
    phone: '+966501234014',
    status: 'APPROVED',
    priceTier: 'ELITE',
    specialties: 'OPERATIONS_MANAGER,PROJECT_MANAGER',
    industries: 'OIL_GAS,CONSTRUCTION',
    languages: 'AR,EN',
    yearsExperience: 18,
    rating: 4.9,
    totalInterviews: 71,
    appliedAt: '2024-04-05T10:00:00Z',
    idVerified: true,
    bio: 'Operations director with 18 years managing mega-projects in oil & gas and construction sectors.',
    bioAr: 'مدير عمليات مع 18 عاماً في إدارة المشاريع الضخمة في قطاعات النفط والبناء.',
    linkedInUrl: 'https://linkedin.com/in/khalid-almutairi',
    videoIntroUrl: null,
  },
  {
    id: 'int-006',
    fullName: 'Noura Al-Qahtani',
    fullNameAr: 'نورة القحطاني',
    email: 'noura@example.com',
    phone: '+966501234015',
    status: 'APPROVED',
    priceTier: 'STANDARD',
    specialties: 'GRAPHIC_DESIGNER,SOFTWARE_ENGINEER',
    industries: 'TECHNOLOGY,CREATIVE',
    languages: 'AR',
    yearsExperience: 7,
    rating: 4.5,
    totalInterviews: 38,
    appliedAt: '2024-09-01T10:00:00Z',
    idVerified: true,
    bio: 'Creative technologist blending design thinking with full-stack engineering. UI/UX and brand identity specialist.',
    bioAr: 'مبدعة تقنية تجمع بين التفكير التصميمي والهندسة. متخصصة في واجهات المستخدم.',
    linkedInUrl: null,
    videoIntroUrl: null,
  },
  // ── REJECTED ──
  {
    id: 'adm-010',
    fullName: 'Yazeed Al-Raddadi',
    fullNameAr: 'يزيد الرادادي',
    email: 'yazeed@example.com',
    phone: '+966501234020',
    status: 'REJECTED',
    priceTier: 'STANDARD',
    specialties: 'CUSTOMER_SERVICE',
    industries: 'RETAIL',
    languages: 'AR',
    yearsExperience: 1,
    rating: 0,
    totalInterviews: 0,
    appliedAt: '2024-11-01T10:00:00Z',
    idVerified: false,
    rejectionReason: 'Insufficient experience for the role.',
    bio: null,
    bioAr: null,
    linkedInUrl: null,
    videoIntroUrl: null,
  },
  {
    id: 'adm-011',
    fullName: 'Mona Al-Zahrani',
    fullNameAr: 'منى الزهراني',
    email: 'mona@example.com',
    phone: '+966501234021',
    status: 'REJECTED',
    priceTier: 'STANDARD',
    specialties: 'DATA_ANALYST',
    industries: 'TECHNOLOGY',
    languages: 'AR,EN',
    yearsExperience: 2,
    rating: 0,
    totalInterviews: 0,
    appliedAt: '2024-11-10T10:00:00Z',
    idVerified: true,
    rejectionReason: 'ID document could not be verified.',
    bio: 'Data analyst with 2 years in tech.',
    bioAr: 'محللة بيانات مع عامين في التقنية.',
    linkedInUrl: null,
    videoIntroUrl: null,
  },
  // ── SUSPENDED ──
  {
    id: 'adm-012',
    fullName: 'Bader Al-Harbi',
    fullNameAr: 'بادر الحربي',
    email: 'bader@example.com',
    phone: '+966501234022',
    status: 'SUSPENDED',
    priceTier: 'PREMIUM',
    specialties: 'PROJECT_MANAGER',
    industries: 'CONSTRUCTION,GOVERNMENT',
    languages: 'AR',
    yearsExperience: 9,
    rating: 3.8,
    totalInterviews: 15,
    appliedAt: '2024-03-15T10:00:00Z',
    idVerified: true,
    suspensionReason: 'Multiple candidate complaints about professionalism.',
    bio: 'Project manager with 9 years in construction and government projects.',
    bioAr: 'مدير مشاريع مع 9 أعوام في البناء والمشاريع الحكومية.',
    linkedInUrl: 'https://linkedin.com/in/bader-alharbi',
    videoIntroUrl: null,
  },
];

// GET /api/admin/interviewers — list all interviewers with optional status filter
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const status = searchParams.get('status') || '';

    // ── Try DB first ──
    try {
      const { db } = await import('@/lib/db');
      const where: Record<string, unknown> = {};
      if (status) {
        where.status = status;
      }

      const [dbInterviewers, total] = await Promise.all([
        db.interviewer.findMany({
          where,
          orderBy: { createdAt: 'desc' },
          select: {
            id: true,
            fullName: true,
            fullNameAr: true,
            phone: true,
            status: true,
            priceTier: true,
            specialties: true,
            industries: true,
            languages: true,
            yearsExperience: true,
            rating: true,
            totalInterviews: true,
            createdAt: true,
            idVerified: true,
            bio: true,
            bioAr: true,
            linkedInUrl: true,
            videoIntroUrl: true,
          },
        }),
        db.interviewer.count({ where }),
      ]);

      return NextResponse.json({
        interviewers: dbInterviewers,
        total,
      });
    } catch (dbErr) {
      console.warn('[GET /api/admin/interviewers] DB unavailable, using mock data:', dbErr);
    }

    // ── Mock mode ──
    let filtered = [...MOCK_ADMIN_INTERVIEWERS];

    if (status) {
      filtered = filtered.filter((i) => i.status === status.toUpperCase());
    }

    return NextResponse.json({
      interviewers: filtered,
      total: filtered.length,
    });
  } catch (err) {
    console.error('GET /api/admin/interviewers error:', err);
    return NextResponse.json(
      {
        error: {
          ar: 'حدث خطأ أثناء جلب قائمة المقابلين',
          en: 'Error fetching interviewers list',
        },
      },
      { status: 500 },
    );
  }
}
