import React from 'react';
import path from 'path';
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  Font,
  renderToBuffer,
} from '@react-pdf/renderer';
import QRCode from 'qrcode';
import type { CoachScoreResult } from './types';
import { getInterviewConfig } from './config';

const colors = {
  navy: '#0f172a',
  teal: '#14b8a6',
  ink: '#0f172a',
  muted: '#64748b',
  line: '#e2e8f0',
  paper: '#f8fafc',
  white: '#ffffff',
};

try {
  Font.register({
    family: 'Amiri',
    fonts: [
      {
        src: path.join(process.cwd(), 'public/fonts/Amiri-Regular.ttf'),
        fontWeight: 'normal',
      },
      {
        src: path.join(process.cwd(), 'public/fonts/Amiri-Bold.ttf'),
        fontWeight: 'bold',
      },
    ],
  });
} catch (err) {
  console.error('[coach/passport-pdf] font register failed', err);
}

const styles = StyleSheet.create({
  page: {
    padding: 0,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: colors.ink,
    backgroundColor: colors.white,
  },
  pageAr: {
    fontFamily: 'Amiri',
  },
  header: {
    backgroundColor: colors.navy,
    paddingVertical: 22,
    paddingHorizontal: 36,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brand: {
    color: colors.white,
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
  },
  brandAr: {
    fontFamily: 'Amiri',
    fontWeight: 'bold',
  },
  headerTitle: {
    color: colors.teal,
    fontSize: 12,
    marginTop: 4,
    fontFamily: 'Helvetica-Bold',
  },
  body: {
    paddingHorizontal: 36,
    paddingTop: 28,
    paddingBottom: 28,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 14,
    backgroundColor: colors.paper,
    marginBottom: 16,
  },
  row: { flexDirection: 'row', marginBottom: 6 },
  label: { width: 100, color: colors.muted, fontSize: 9 },
  value: { flex: 1, fontFamily: 'Helvetica-Bold', fontSize: 10 },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    gap: 18,
  },
  scoreNumber: {
    fontSize: 48,
    fontFamily: 'Helvetica-Bold',
    color: colors.navy,
  },
  badge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 3,
    borderColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  badgeText: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: colors.teal,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.navy,
    marginBottom: 8,
    marginTop: 4,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  gridItem: {
    width: '48%',
    marginBottom: 10,
    padding: 8,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 6,
  },
  barTrack: {
    height: 5,
    backgroundColor: colors.line,
    borderRadius: 3,
    marginTop: 4,
  },
  barFill: { height: 5, backgroundColor: colors.teal, borderRadius: 3 },
  twoCol: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  col: { width: '48%' },
  bullet: { marginBottom: 4, fontSize: 9, color: colors.ink },
  qrWrap: { alignItems: 'center', marginTop: 18, marginBottom: 10 },
  footer: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    marginTop: 10,
    paddingTop: 10,
    fontSize: 8,
    color: colors.muted,
    textAlign: 'center',
  },
});

export type PassportPdfInput = {
  candidateName: string;
  role: string;
  industry: string;
  seniority: string;
  language: string;
  interviewDate: string;
  score: CoachScoreResult;
  verificationId: string;
  verifyUrl: string;
  /** When true, use Arabic/RTL layout */
  rtl?: boolean;
};

function PassportDoc({
  data,
  qrDataUrl,
}: {
  data: PassportPdfInput;
  qrDataUrl: string | null;
}) {
  const cfg = getInterviewConfig();
  const rtl = Boolean(data.rtl);
  const title = rtl
    ? cfg.brand.passportTitleAr || 'جواز المقابلة'
    : cfg.brand.passportTitle;
  const L = rtl
    ? {
        candidate: 'المرشح',
        date: 'التاريخ',
        role: 'الدور',
        industry: 'القطاع',
        seniority: 'المستوى',
        language: 'اللغة',
        overall: 'الدرجة الكلية',
        competencies: 'الكفاءات',
        strengths: 'نقاط القوة',
        improvements: 'للتحسين',
        scan: 'امسح للتحقق',
        generated: 'تم إنشاء هذا الجواز بواسطة مدرب المقابلات الذكي في مقابلة',
      }
    : {
        candidate: 'Candidate',
        date: 'Date',
        role: 'Role',
        industry: 'Industry',
        seniority: 'Seniority',
        language: 'Language',
        overall: 'Overall score',
        competencies: 'Competencies',
        strengths: 'Strengths',
        improvements: 'Improvements',
        scan: 'Scan to verify',
        generated: 'This passport was generated by Muqabaleh AI Interview Coach',
      };

  const comps = [...data.score.competencyBreakdown];
  while (comps.length < 6) {
    comps.push({ name: 'Leadership', score: data.score.overallScore });
  }

  const dirStyle = rtl ? { flexDirection: 'row-reverse' as const } : {};

  return (
    <Document>
      <Page size="A4" style={[styles.page, rtl ? styles.pageAr : {}]}>
        <View style={[styles.header, dirStyle]}>
          <View>
            <Text style={[styles.brand, rtl ? styles.brandAr : {}]}>
              {rtl ? cfg.brand.nameAr : cfg.brand.name}
            </Text>
            <Text style={[styles.headerTitle, rtl ? styles.brandAr : {}]}>
              {title}
            </Text>
          </View>
          <Text style={{ color: colors.teal, fontSize: 10 }}>
            {rtl ? 'شهادة موثّقة' : 'Verified credential'}
          </Text>
        </View>

        <View style={styles.body}>
          <View style={styles.card}>
            {(
              [
                [L.candidate, data.candidateName],
                [L.date, data.interviewDate],
                [L.role, data.role],
                [L.industry, data.industry],
                [L.seniority, data.seniority],
                [L.language, data.language],
              ] as const
            ).map(([label, value]) => (
              <View key={label} style={[styles.row, dirStyle]}>
                <Text style={styles.label}>{label}</Text>
                <Text style={[styles.value, rtl ? { fontFamily: 'Amiri', fontWeight: 'bold' } : {}]}>
                  {value}
                </Text>
              </View>
            ))}
          </View>

          <View style={[styles.scoreRow, dirStyle]}>
            <View>
              <Text style={{ color: colors.muted, fontSize: 9, marginBottom: 4 }}>
                {L.overall}
              </Text>
              <Text style={styles.scoreNumber}>{data.score.overallScore}</Text>
            </View>
            <View style={styles.badge}>
              <Text style={styles.badgeText}>{data.score.grade}</Text>
            </View>
          </View>

          <Text style={[styles.sectionTitle, rtl ? { fontFamily: 'Amiri', fontWeight: 'bold' } : {}]}>
            {L.competencies}
          </Text>
          <View style={styles.grid}>
            {comps.slice(0, 6).map((c) => (
              <View key={c.name} style={styles.gridItem}>
                <View style={[{ flexDirection: 'row', justifyContent: 'space-between' }, dirStyle]}>
                  <Text style={{ fontSize: 9 }}>{c.name}</Text>
                  <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>
                    {c.score}
                  </Text>
                </View>
                <View style={styles.barTrack}>
                  <View
                    style={[
                      styles.barFill,
                      { width: `${Math.max(0, Math.min(100, c.score))}%` },
                    ]}
                  />
                </View>
              </View>
            ))}
          </View>

          <View style={[styles.twoCol, dirStyle]}>
            <View style={styles.col}>
              <Text style={[styles.sectionTitle, rtl ? { fontFamily: 'Amiri', fontWeight: 'bold' } : {}]}>
                {L.strengths}
              </Text>
              {data.score.strengths.slice(0, 3).map((s, i) => (
                <Text key={i} style={[styles.bullet, rtl ? { fontFamily: 'Amiri' } : {}]}>
                  ✓ {s}
                </Text>
              ))}
            </View>
            <View style={styles.col}>
              <Text style={[styles.sectionTitle, rtl ? { fontFamily: 'Amiri', fontWeight: 'bold' } : {}]}>
                {L.improvements}
              </Text>
              {data.score.improvements.slice(0, 3).map((s, i) => (
                <Text key={i} style={[styles.bullet, rtl ? { fontFamily: 'Amiri' } : {}]}>
                  → {s}
                </Text>
              ))}
            </View>
          </View>

          <View style={styles.qrWrap}>
            {qrDataUrl ? (
              <Image src={qrDataUrl} style={{ width: 120, height: 120 }} />
            ) : null}
            <Text style={{ marginTop: 6, fontSize: 9, color: colors.muted }}>
              {L.scan}
            </Text>
          </View>

          <View style={styles.footer}>
            <Text>
              {data.verificationId} · {data.verifyUrl}
            </Text>
            <Text style={{ marginTop: 3 }}>{L.generated}</Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}

export async function buildPassportPdfBuffer(data: PassportPdfInput): Promise<Buffer> {
  let qrDataUrl: string | null = null;
  try {
    qrDataUrl = await QRCode.toDataURL(data.verifyUrl, {
      margin: 1,
      width: 240,
      errorCorrectionLevel: 'M',
    });
  } catch (err) {
    console.error('[coach/passport-pdf] QR failed', err);
  }

  const rtl =
    data.rtl ??
    (/arabic|عربي|العربية/i.test(data.language) ||
      data.language === 'ar' ||
      data.language === 'AR');

  const buf = await renderToBuffer(
    <PassportDoc data={{ ...data, rtl }} qrDataUrl={qrDataUrl} />,
  );
  return Buffer.from(buf);
}
