/** Bilingual admin UI labels — professional Arabic meaning (not literal). Muqabaleh only. */

export type Bi = { ar: string; en: string };

export const L = {
  brand: { ar: 'لوحة تحكم المسؤول العام — مقابلة', en: 'Muqabaleh Super Admin Control' },
  systemAdmin: { ar: 'المسؤول العام', en: 'Super Admin' },
  signOut: { ar: 'تسجيل الخروج', en: 'Sign Out' },
  back: { ar: 'رجوع', en: 'Back' },
  dashboard: { ar: 'لوحة التحكم', en: 'Dashboard' },
  systemHealth: { ar: 'صحة النظام', en: 'System Health' },
  runSystemsCheck: { ar: 'تشغيل فحص الأنظمة', en: 'Run systems check' },
  search: { ar: 'بحث', en: 'Search' },
  refresh: { ar: 'تحديث', en: 'Refresh' },
  create: { ar: 'إنشاء', en: 'Create' },
  edit: { ar: 'تعديل', en: 'Edit' },
  delete: { ar: 'حذف', en: 'Delete' },
  save: { ar: 'حفظ', en: 'Save' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  actions: { ar: 'إجراءات', en: 'Actions' },
  status: { ar: 'الحالة', en: 'Status' },
  loading: { ar: 'جارٍ التحميل…', en: 'Loading…' },
  empty: { ar: 'لا توجد بيانات', en: 'No data yet' },
  error: { ar: 'حدث خطأ', en: 'Something went wrong' },
  success: { ar: 'تم بنجاح', en: 'Success' },
  theme: { ar: 'المظهر', en: 'Theme' },
  light: { ar: 'فاتح', en: 'Light' },
  dark: { ar: 'داكن', en: 'Dark' },
  collapse: { ar: 'طي القائمة', en: 'Collapse sidebar' },
  expand: { ar: 'توسيع القائمة', en: 'Expand sidebar' },
  home: { ar: 'الرئيسية', en: 'Home' },
  overview: { ar: 'نظرة عامة', en: 'Overview' },
  exportCsv: { ar: 'تصدير CSV', en: 'Export CSV' },
  exportExcel: { ar: 'تصدير Excel', en: 'Export Excel' },
  activate: { ar: 'تفعيل', en: 'Activate' },
  deactivate: { ar: 'تعطيل', en: 'Deactivate' },
  emailAction: { ar: 'إرسال بريد', en: 'Email' },
  bulkActions: { ar: 'إجراءات جماعية', en: 'Bulk actions' },
  filter: { ar: 'تصفية', en: 'Filter' },
  sort: { ar: 'فرز', en: 'Sort' },
  // Users — المستخدمون
  users: { ar: 'المستخدمون', en: 'Users' },
  allUsers: { ar: 'الجميع', en: 'All Users' },
  candidates: { ar: 'المرشحون', en: 'Candidates' },
  admins: { ar: 'المسؤولون', en: 'Admins' },
  companies: { ar: 'الشركات', en: 'Companies' },
  // Interviews — المقابلات
  interviews: { ar: 'المقابلات', en: 'Interviews' },
  templates: { ar: 'نماذج المقابلات', en: 'Templates' },
  questions: { ar: 'بنك الأسئلة', en: 'Question Bank' },
  sessions: { ar: 'الجلسات المباشرة', en: 'Live Sessions' },
  rubrics: { ar: 'معايير التقييم', en: 'Scoring Rubrics' },
  // Partners — الشركاء
  partners: { ar: 'الشركاء', en: 'Partners' },
  whitelabel: { ar: 'العلامة التجارية الخاصة', en: 'Whitelabel' },
  applications: { ar: 'طلبات الانضمام للشراكة', en: 'Applications' },
  revenueShare: { ar: 'مشاركة الأرباح', en: 'Revenue Share' },
  revenue: { ar: 'مشاركة الأرباح', en: 'Revenue Share' },
  // Billing — الفوترة
  billing: { ar: 'الفوترة', en: 'Billing' },
  plans: { ar: 'باقات الاشتراك', en: 'Plans' },
  subscriptions: { ar: 'الاشتراكات النشطة', en: 'Active Subscriptions' },
  invoices: { ar: 'الفواتير', en: 'Invoices' },
  // Payments — المدفوعات
  payments: { ar: 'المدفوعات', en: 'Payments' },
  transactions: { ar: 'سجل العمليات المالية', en: 'Transactions' },
  payouts: { ar: 'التحويلات للشركاء', en: 'Payouts' },
  financialOverview: { ar: 'الملخص المالي', en: 'Financial Overview' },
  // AI — الذكاء الاصطناعي
  aiApis: { ar: 'الذكاء الاصطناعي', en: 'AI & APIs' },
  providers: { ar: 'خدمات الذكاء الاصطناعي', en: 'Providers' },
  keys: { ar: 'مفاتيح API', en: 'API Keys' },
  prompts: { ar: 'التعليمات النصية', en: 'Prompts' },
  usage: { ar: 'الاستهلاك والتكلفة', en: 'Usage' },
  // Content — المحتوى
  content: { ar: 'المحتوى', en: 'Content' },
  landing: { ar: 'الصفحة الهبوط', en: 'Landing Page' },
  emails: { ar: 'قوالب البريد الإلكتروني', en: 'Emails' },
  // Analytics — التحليلات
  analytics: { ar: 'التحليلات', en: 'Analytics' },
  website: { ar: 'أداء الموقع', en: 'Website' },
  behavior: { ar: 'تحليلات سلوك المستخدمين', en: 'Behavior' },
  // Settings — الإعدادات
  settings: { ar: 'الإعدادات', en: 'Settings' },
  general: { ar: 'الإعدادات العامة', en: 'General' },
  security: { ar: 'إعدادات الحماية', en: 'Security' },
  access: { ar: 'إدارة صلاحيات الوصول', en: 'Access' },
  backup: { ar: 'النسخ الاحتياطي والصيانة', en: 'Backup' },
  // Support — الدعم الفني
  support: { ar: 'الدعم الفني', en: 'Support' },
  tickets: { ar: 'طلبات الدعم الفني', en: 'Tickets' },
  chat: { ar: 'الدردشة المباشرة', en: 'Chat' },
  // Top-level
  notifications: { ar: 'مركز التنبيهات', en: 'Notification Center' },
  alerts: { ar: 'التنبيهات', en: 'Alerts' },
  alertsEmails: { ar: 'تنبيهات وبريد النظام', en: 'Alerts & system email' },
  audit: { ar: 'سجلات النشاط', en: 'Audit Logs' },
  applicants: { ar: 'قاعدة بيانات المتقدمين', en: 'Applicants' },
  jeannieOps: { ar: 'عمليات جيني', en: 'Jeannie Ops' },
  refund: { ar: 'استرداد المبلغ', en: 'Refund' },
  enable2fa: { ar: 'تفعيل المصادقة الثنائية', en: 'Enable 2FA' },
  verify2fa: { ar: 'رمز المصادقة', en: 'Verification code' },
  // Dashboard widgets
  todaysInterviews: { ar: 'مقابلات اليوم', en: "Today's Interviews" },
  newSignups: { ar: 'حسابات جديدة اليوم', en: 'New accounts today' },
  revenueToday: { ar: 'الإيرادات اليومية', en: 'Revenue Today' },
  activeCompanies: { ar: 'الشركات النشطة', en: 'Active Companies' },
  pendingTickets: { ar: 'طلبات الدعم المعلقة', en: 'Pending Support Tickets' },
  apiHealth: { ar: 'حالة خدمات API', en: 'API Health Status' },
  visitors24h: { ar: 'زوّار فريدون (٢٤ ساعة)', en: 'Unique visitors (24h)' },
  peopleSection: { ar: 'المستخدمون (حسابات مسجّلة)', en: 'People (registered accounts)' },
  visitsSection: { ar: 'زيارات الموقع (بدون حساب)', en: 'Site visits (anonymous)' },
  interviewsSection: { ar: 'المقابلات', en: 'Interviews' },
  moneySection: { ar: 'المال', en: 'Money' },
  jobsSection: { ar: 'الوظائف', en: 'Jobs' },
  usersTotal: { ar: 'إجمالي الحسابات', en: 'Total accounts' },
  users7d: { ar: 'حسابات جديدة (٧ أيام)', en: 'New accounts (7d)' },
  loggedIn24h: { ar: 'دخول خلال ٢٤ ساعة', en: 'Logged in (24h)' },
  pageviews24h: { ar: 'مشاهدات الصفحات (٢٤ ساعة)', en: 'Pageviews (24h)' },
  unique7d: { ar: 'زوّار فريدون (٧ أيام)', en: 'Unique visitors (7d)' },
  pageviews7d: { ar: 'مشاهدات الصفحات (٧ أيام)', en: 'Pageviews (7d)' },
  interviews7d: { ar: 'مقابلات ٧ أيام', en: 'Interviews (7d)' },
  interviewsTotal: { ar: 'إجمالي المقابلات', en: 'Total interviews' },
  liveJobs: { ar: 'وظائف منشورة', en: 'Live job listings' },
  recentSignups: { ar: 'آخر الحسابات الجديدة', en: 'Latest accounts' },
  topPages: { ar: 'أكثر الصفحات زيارة (٧ أيام)', en: 'Top pages (7d)' },
  activeJeannie: { ar: 'اشتراكات جيني النشطة', en: 'Active Jeannie subs' },
  revenue30d: { ar: 'إيراد ٣٠ يوماً', en: 'Revenue (30d)' },
  revenueTrend: { ar: 'اتجاه الإيرادات', en: 'Revenue trend' },
  completionRate: { ar: 'نسبة إكمال المقابلات', en: 'Interview completion rate' },
  userGrowth: { ar: 'نمو المستخدمين حسب النوع', en: 'User growth by type (B2C vs B2B)' },
  topIndustries: { ar: 'أكثر القطاعات مقابلات', en: 'Top industries interviewed for' },
  // Misc ops kept for legacy routes
  legacyOps: { ar: 'عمليات إضافية', en: 'Extra Ops' },
  interviewers: { ar: 'المحاورون', en: 'Interviewers' },
  bookings: { ar: 'الحجوزات', en: 'Bookings' },
  coachOverview: { ar: 'نظرة جيني / الجواز', en: 'Jeannie / Passport Ops' },
  // Expanded ops (2026)
  jobsBoard: { ar: 'لوحة الوظائف', en: 'Jobs Board' },
  student100: { ar: 'مركز تواصل الطلاب 100', en: 'Student 100 Contact Center' },
  atsAggregator: { ar: 'مجمّع ATS', en: 'ATS Aggregator' },
  passports: { ar: 'جوازات المقابلة', en: 'Passports' },
  partnersList: { ar: 'محفظة الشركاء', en: 'Partner Portfolio' },
  b2bJobs: { ar: 'وظائف الشركات', en: 'B2B Jobs' },
  b2bApplications: { ar: 'طلبات التوظيف', en: 'B2B Applications' },
  entitlements: { ar: 'صلاحيات جيني', en: 'Jeannie Entitlements' },
  emailQueue: { ar: 'طابور البريد', en: 'Email Queue' },
  mockSessions: { ar: 'جلسات المحاكاة', en: 'Mock Sessions' },
  partnerPayouts: { ar: 'مدفوعات الشركاء', en: 'Partner Payouts' },
  interviewerPayouts: { ar: 'مدفوعات المحاورين', en: 'Interviewer Payouts' },
} as const satisfies Record<string, Bi>;

export type LabelKey = keyof typeof L;

export function bi(key: LabelKey): Bi {
  return L[key];
}
