/** Bilingual admin UI labels — Arabic + English shown simultaneously. Muqabaleh only. */

export type Bi = { ar: string; en: string };

export const L = {
  brand: { ar: 'لوحة تحكم مقابلة', en: 'Muqabaleh Admin' },
  systemAdmin: { ar: 'مشرف أعلى', en: 'Super Admin' },
  signOut: { ar: 'تسجيل الخروج', en: 'Sign Out' },
  back: { ar: 'رجوع', en: 'Back' },
  dashboard: { ar: 'لوحة القيادة', en: 'Dashboard' },
  search: { ar: 'بحث', en: 'Search' },
  refresh: { ar: 'تحديث', en: 'Refresh' },
  create: { ar: 'إنشاء', en: 'Create' },
  edit: { ar: 'تعديل', en: 'Edit' },
  delete: { ar: 'حذف', en: 'Delete' },
  save: { ar: 'حفظ', en: 'Save' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  actions: { ar: 'إجراءات', en: 'Actions' },
  status: { ar: 'الحالة', en: 'Status' },
  loading: { ar: 'جارٍ التحميل…', en: 'Loading…' },
  empty: { ar: 'لا توجد بيانات', en: 'No data yet' },
  error: { ar: 'حدث خطأ', en: 'Something went wrong' },
  success: { ar: 'تم بنجاح', en: 'Success' },
  theme: { ar: 'المظهر', en: 'Theme' },
  light: { ar: 'فاتح', en: 'Light' },
  dark: { ar: 'داكن', en: 'Dark' },
  collapse: { ar: 'طي القائمة', en: 'Collapse sidebar' },
  expand: { ar: 'توسيع القائمة', en: 'Expand sidebar' },
  home: { ar: 'الرئيسية', en: 'Home' },
  overview: { ar: 'نظرة عامة', en: 'Overview' },
  users: { ar: 'المستخدمون', en: 'Users' },
  allUsers: { ar: 'كل المستخدمين', en: 'All Users' },
  candidates: { ar: 'المرشحون', en: 'Candidates' },
  admins: { ar: 'المشرفون', en: 'Admins' },
  companies: { ar: 'الشركات', en: 'Companies' },
  interviews: { ar: 'المقابلات', en: 'Interviews' },
  templates: { ar: 'القوالب', en: 'Templates' },
  questions: { ar: 'الأسئلة', en: 'Questions' },
  sessions: { ar: 'الجلسات', en: 'Sessions' },
  rubrics: { ar: 'معايير التقييم', en: 'Rubrics' },
  partners: { ar: 'الشركاء', en: 'Partners' },
  whitelabel: { ar: 'العلامة البيضاء', en: 'White Label' },
  applications: { ar: 'الطلبات', en: 'Applications' },
  revenue: { ar: 'الإيرادات', en: 'Revenue' },
  billing: { ar: 'الفوترة', en: 'Billing' },
  plans: { ar: 'الباقات', en: 'Plans' },
  subscriptions: { ar: 'الاشتراكات', en: 'Subscriptions' },
  invoices: { ar: 'الفواتير', en: 'Invoices' },
  payments: { ar: 'المدفوعات', en: 'Payments' },
  transactions: { ar: 'المعاملات', en: 'Transactions' },
  payouts: { ar: 'المدفوعات للمحاورين', en: 'Payouts' },
  aiApis: { ar: 'واجهات الذكاء الاصطناعي', en: 'AI APIs' },
  providers: { ar: 'المزوّدون', en: 'Providers' },
  keys: { ar: 'المفاتيح', en: 'API Keys' },
  prompts: { ar: 'الأوامر', en: 'Prompts' },
  usage: { ar: 'الاستخدام', en: 'Usage' },
  content: { ar: 'المحتوى', en: 'Content' },
  landing: { ar: 'الصفحة الرئيسية', en: 'Landing' },
  emails: { ar: 'البريد', en: 'Emails' },
  notifications: { ar: 'الإشعارات', en: 'Notifications' },
  analytics: { ar: 'التحليلات', en: 'Analytics' },
  website: { ar: 'الموقع', en: 'Website' },
  behavior: { ar: 'السلوك', en: 'Behavior' },
  settings: { ar: 'الإعدادات', en: 'Settings' },
  general: { ar: 'عام', en: 'General' },
  security: { ar: 'الأمان', en: 'Security' },
  access: { ar: 'الصلاحيات', en: 'Access' },
  backup: { ar: 'النسخ الاحتياطي', en: 'Backup' },
  support: { ar: 'الدعم', en: 'Support' },
  tickets: { ar: 'التذاكر', en: 'Tickets' },
  chat: { ar: 'المحادثة', en: 'Chat' },
  audit: { ar: 'سجل التدقيق', en: 'Audit Trail' },
  applicants: { ar: 'المتقدمون', en: 'Applicants' },
  refund: { ar: 'استرداد', en: 'Refund' },
  enable2fa: { ar: 'تفعيل التحقق الثنائي', en: 'Enable 2FA' },
  verify2fa: { ar: 'رمز التحقق', en: 'Verification code' },
  legacyOps: { ar: 'عمليات سابقة', en: 'Legacy Ops' },
  interviewers: { ar: 'المحاورون', en: 'Interviewers' },
  bookings: { ar: 'الحجوزات', en: 'Bookings' },
} as const satisfies Record<string, Bi>;

export type LabelKey = keyof typeof L;

export function bi(key: LabelKey): Bi {
  return L[key];
}
